name: CI
on: [push]
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install isort mypy black
      - name: Lint
        run: |
          # stop the build if there are Python syntax errors or undefined names
          isort app
          back app
          mypy app
      - name: Test with pytest
        run: |
          pytest tests

